/* Mirror49 — roadmap data
   Transcribed in full from: 49-Day Applied AI Engineer Execution Roadmap
   (13 September – 31 October 2026, prepared for Utkarsh Katiyar)
   Nothing here is invented — every field maps directly to the source PDF. */

const ROADMAP_START = new Date(2026, 8, 13); // 13 Sep 2026 (month index 8 = September)
const ROADMAP_END_DAYS = 49;

const DAILY_CHECKLIST_LABELS = [
  "Theory",
  "Implementation",
  "Tests",
  "Failure drill",
  "DSA review",
  "Explain aloud",
];

const CONTRACT = {
  title: "The Contract",
  subtitle: "How to use the next 49 days",
  rows: [
    { label: "Daily commitment", value: "AI: 2.5-3 hours | DSA: 1.5-2 hours | Work continues normally" },
    { label: "Learning ratio", value: "25% watching/reading | 60% implementation | 15% revision and interviews" },
    { label: "Primary language", value: "Python for AI engineering and DSA" },
    { label: "Single capstone", value: "Agent Reliability Lab - do not start another unrelated project" },
    { label: "Weekly rhythm", value: "Days 1-6 build and practice; Day 7 integrates, tests and interviews" },
    { label: "Evidence standard", value: "Working code, tests, measured results, failure drills and spoken explanation" },
  ],
  rules: [
    "For every hour of content, complete at least two hours of implementation.",
    "Never paste generated code you cannot explain or recreate.",
    "Every feature needs tests, one induced failure and a written trade-off.",
    "Failed DSA problems return after 1, 3, 7 and 14 days.",
    "Do not postpone applications until Day 49.",
    "Missing one day does not change the plan: recover within the same week; never shift the finish line.",
  ],
  honestTarget:
    "Seven weeks cannot manufacture three years of production experience. It can make you interview-ready for Applied AI / GenAI / Agentic AI roles if you complete the implementation and can defend it without assistance. This roadmap does not target research-scientist, CUDA, foundation-model-training or mathematics-heavy ML roles.",
};

const DAILY_COMPLETION_DEFINITION = [
  "Theory notes are concise and written in your words.",
  "Implementation runs and meaningful tests pass.",
  "At least one failure or edge case has been exercised.",
  "DSA attempts include brute force, optimal reasoning and complexity.",
  "The day's concept can be explained aloud without opening notes.",
  "Changes are committed with an honest message.",
];

const WEEKS = [
  {
    week: 1,
    dateRange: "13 Sep - 19 Sep 2026",
    title: "Python, APIs and ML Foundations",
    aiFocus: "Python, APIs and ML Foundations",
    dsaFocus: "Arrays, strings, hashing, prefix sums",
    outcome: "Write typed Python naturally, build a tested FastAPI service, use PostgreSQL, and explain essential ML metrics.",
    gate: [
      "Explain the event loop and blocking I/O",
      "Build tested CRUD without copying",
      "Use transactions and migrations",
      "Explain precision, recall, F1 and cosine similarity",
    ],
  },
  {
    week: 2,
    dateRange: "20 Sep - 26 Sep 2026",
    title: "Transformers, LLM APIs and Tool Calling",
    aiFocus: "Transformers, LLM APIs and Tool Calling",
    dsaFocus: "Two pointers, sliding window, intervals",
    outcome: "Understand transformer data flow and build a provider-independent, validated, streaming tool-use loop.",
    gate: [
      "Explain a transformer in five minutes",
      "Implement a manual agent/tool loop",
      "Validate every model-produced argument",
      "Handle rate limits, malformed outputs and stream interruption",
    ],
  },
  {
    week: 3,
    dateRange: "27 Sep - 03 Oct 2026",
    title: "Production RAG and Retrieval Evaluation",
    aiFocus: "Production RAG and Retrieval Evaluation",
    dsaFocus: "Stacks, binary search, linked lists",
    outcome: "Build ingestion, hybrid retrieval, reranking and measurable retrieval/answer evaluation.",
    gate: [
      "Justify chunking and top-k with data",
      "Explain dense, sparse and hybrid retrieval",
      "Measure Recall@k and MRR",
      "Support update, deletion and tenant isolation",
    ],
  },
  {
    week: 4,
    dateRange: "04 Oct - 10 Oct 2026",
    title: "Agents, LangGraph, Memory and MCP",
    aiFocus: "Agents, LangGraph, Memory and MCP",
    dsaFocus: "Trees, heaps and tries",
    outcome: "Build explicit stateful workflows with durable execution, safe tools, approval and controlled memory.",
    gate: [
      "Choose workflow vs agent deliberately",
      "Persist and resume graph state",
      "Require approval for write tools",
      "Explain MCP client/server boundaries",
    ],
  },
  {
    week: 5,
    dateRange: "11 Oct - 17 Oct 2026",
    title: "Queues, Distributed Systems and Reliability",
    aiFocus: "Queues, Distributed Systems and Reliability",
    dsaFocus: "Graphs, union-find and shortest paths",
    outcome: "Operate long-running AI work safely using Celery/RabbitMQ, idempotency and resilience patterns.",
    gate: [
      "Explain at-least-once delivery",
      "Prevent duplicate side effects",
      "Recover from worker/provider failure",
      "Design the low-latency voice-agent scenario",
    ],
  },
  {
    week: 6,
    dateRange: "18 Oct - 24 Oct 2026",
    title: "Evals, Observability, Security and Deployment",
    aiFocus: "Evals, Observability, Security and Deployment",
    dsaFocus: "Backtracking, greedy and dynamic programming",
    outcome: "Measure quality, trace behaviour, defend tools/data and deploy through a repeatable pipeline.",
    gate: [
      "Prove prompt/model improvement with evals",
      "Trace API-to-worker-to-tool execution",
      "Defend against injection and leakage",
      "Deploy and roll back safely",
    ],
  },
  {
    week: 7,
    dateRange: "25 Oct - 31 Oct 2026",
    title: "Interview Conversion and Final Proof",
    aiFocus: "Interview Conversion and Final Proof",
    dsaFocus: "Advanced patterns, mixed mocks and AI coding",
    outcome: "Convert seven weeks of implementation into defensible interviews, portfolio evidence and applications.",
    gate: [
      "Solve unseen Mediums in 30-35 minutes",
      "Pass four mock interview formats",
      "Demo with measured evidence",
      "Position honestly as Applied AI Engineer",
    ],
  },
];

/* Learning-resource links, organised by the day whose topic they support.
   Each resource: { title, platform, type (Video|Playlist|Course|Documentation), url, label? }
   These are pointers only — nothing is embedded, nothing here logs progress by itself. */

const RESOURCES_BY_DAY = {
  1: [
    { title: "Python for AI & Agents", platform: "Dave Ebbelaar", type: "Playlist",
      url: "https://www.youtube.com/playlist?list=PL-Y17yukoyy0SupAJSPQYg_Lvre9Kt9EG", label: "Primary" },
  ],
  3: [
    { title: "AsyncIO Walkthrough", platform: "Real Python", type: "Documentation",
      url: "https://realpython.com/async-io-python/", label: "Primary" },
    { title: "Python videos", platform: "mCoding", type: "Playlist",
      url: "https://www.youtube.com/@mCoding/videos", label: "Selective" },
  ],
  4: [
    { title: "FastAPI Course", platform: "freeCodeCamp", type: "Course",
      url: "https://www.youtube.com/watch?v=0sOvCWFmrtA", label: "Primary" },
    { title: "Official FastAPI Tutorial", platform: "FastAPI", type: "Documentation",
      url: "https://fastapi.tiangolo.com/tutorial/", label: "Reference" },
  ],
  6: [
    { title: "Machine Learning Playlist", platform: "StatQuest", type: "Playlist",
      url: "https://www.youtube.com/playlist?list=PLblh5JKOoLUICTaGLRoHQDuF_7q2GfuJF", label: "Primary" },
    { title: "Neural Networks Playlist", platform: "3Blue1Brown", type: "Playlist",
      url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr", label: "Selective" },
  ],
  7: [
    { title: "NeetCode Roadmap", platform: "NeetCode", type: "Documentation",
      url: "https://neetcode.io/roadmap", label: "Reference" },
    { title: "Striver A2Z DSA Course", platform: "take U forward", type: "Playlist",
      url: "https://www.youtube.com/playlist?list=PLgUwDviBIf0rENwdL0nEH0uGom9no0nyB", label: "Selective" },
  ],
  8: [
    { title: "Intro to Large Language Models", platform: "Andrej Karpathy", type: "Video",
      url: "https://www.youtube.com/watch?v=zjkBMFhNj_g", label: "Primary" },
    { title: "Deep Dive into LLMs like ChatGPT", platform: "Andrej Karpathy", type: "Video",
      url: "https://www.youtube.com/watch?v=7xTGNNLPyMI", label: "Primary" },
  ],
  10: [
    { title: "But What Is a GPT?", platform: "3Blue1Brown", type: "Video",
      url: "https://www.youtube.com/watch?v=wjZofJX0v4M", label: "Primary" },
    { title: "Attention in Transformers", platform: "3Blue1Brown", type: "Video",
      url: "https://www.youtube.com/watch?v=eMlx5fFNoYc", label: "Primary" },
    { title: "Let's Build GPT from Scratch", platform: "Andrej Karpathy", type: "Video",
      url: "https://www.youtube.com/watch?v=kCc8FmEb1nY", label: "Selective" },
  ],
  12: [
    { title: "Structured Outputs Guide", platform: "OpenAI", type: "Documentation",
      url: "https://developers.openai.com/api/docs/guides/structured-outputs", label: "Primary" },
  ],
  13: [
    { title: "Building AI Agents in Pure Python", platform: "Dave Ebbelaar", type: "Video",
      url: "https://www.youtube.com/watch?v=bZzyPscbtI8", label: "Primary" },
  ],
  14: [
    { title: "NeetCode Roadmap", platform: "NeetCode", type: "Documentation",
      url: "https://neetcode.io/roadmap", label: "Reference" },
    { title: "Striver A2Z DSA Course", platform: "take U forward", type: "Playlist",
      url: "https://www.youtube.com/playlist?list=PLgUwDviBIf0rENwdL0nEH0uGom9no0nyB", label: "Selective" },
  ],
  15: [
    { title: "RAG From Scratch", platform: "LangChain", type: "Playlist",
      url: "https://www.youtube.com/playlist?list=PLfaIDFEXuae0gBSJ9T0w7cu7iJZbH3T31", label: "Primary" },
    { title: "Agentic RAG From Scratch", platform: "Dave Ebbelaar", type: "Video",
      url: "https://www.youtube.com/watch?v=RxwjoegpI98", label: "Selective" },
  ],
  17: [
    { title: "Vector Databases: From Embeddings to Applications", platform: "DeepLearning.AI", type: "Course",
      url: "https://www.deeplearning.ai/short-courses/vector-databases-embeddings-applications/", label: "Primary" },
    { title: "LLM Course", platform: "Hugging Face", type: "Course",
      url: "https://huggingface.co/learn/llm-course/chapter1/1", label: "Selective" },
  ],
  20: [
    { title: "Building and Evaluating Advanced RAG", platform: "DeepLearning.AI", type: "Course",
      url: "https://www.deeplearning.ai/short-courses/building-evaluating-advanced-rag/", label: "Primary" },
  ],
  21: [
    { title: "NeetCode Roadmap", platform: "NeetCode", type: "Documentation",
      url: "https://neetcode.io/roadmap", label: "Reference" },
    { title: "Striver A2Z DSA Course", platform: "take U forward", type: "Playlist",
      url: "https://www.youtube.com/playlist?list=PLgUwDviBIf0rENwdL0nEH0uGom9no0nyB", label: "Selective" },
  ],
  22: [
    { title: "How to Build Reliable AI Agents", platform: "Dave Ebbelaar", type: "Video",
      url: "https://www.youtube.com/watch?v=T1Lowy1mnEg", label: "Primary" },
    { title: "Agentic Design Patterns", platform: "DeepLearning.AI", type: "Course",
      url: "https://www.deeplearning.ai/short-courses/ai-agentic-design-patterns-with-autogen/", label: "Selective" },
  ],
  23: [
    { title: "AI Agents in LangGraph", platform: "DeepLearning.AI", type: "Course",
      url: "https://www.deeplearning.ai/courses/ai-agents-in-langgraph", label: "Primary" },
    { title: "LangGraph Essentials", platform: "LangChain Academy", type: "Course",
      url: "https://academy.langchain.com/courses/langgraph-essentials-python", label: "Selective" },
    { title: "Introduction to LangGraph", platform: "LangChain Academy", type: "Course",
      url: "https://academy.langchain.com/courses/intro-to-langgraph", label: "Selective" },
  ],
  25: [
    { title: "Memory Documentation", platform: "LangGraph", type: "Documentation",
      url: "https://docs.langchain.com/oss/python/langgraph/add-memory", label: "Primary" },
  ],
  27: [
    { title: "MCP: Build Rich-Context AI Apps", platform: "DeepLearning.AI", type: "Course",
      url: "https://www.deeplearning.ai/short-courses/mcp-build-rich-context-ai-apps-with-anthropic/", label: "Primary" },
    { title: "Official MCP Introduction", platform: "Model Context Protocol", type: "Documentation",
      url: "https://modelcontextprotocol.io/docs/getting-started/intro", label: "Reference" },
  ],
  28: [
    { title: "Data Structures Playlist", platform: "William Fiset", type: "Playlist",
      url: "https://www.youtube.com/playlist?list=PLDV1Zeh2NRsB6SWUrDFW2RmDotAfPbeHu", label: "Selective" },
    { title: "NeetCode Roadmap", platform: "NeetCode", type: "Documentation",
      url: "https://neetcode.io/roadmap", label: "Reference" },
  ],
  30: [
    { title: "RabbitMQ Tutorial", platform: "Hussein Nasser", type: "Video",
      url: "https://www.youtube.com/watch?v=nFxjaVmFj5E", label: "Primary" },
    { title: "RabbitMQ Official Tutorials", platform: "RabbitMQ", type: "Documentation",
      url: "https://www.rabbitmq.com/tutorials", label: "Reference" },
  ],
  31: [
    { title: "Tasks Documentation", platform: "Celery", type: "Documentation",
      url: "https://docs.celeryq.dev/en/stable/userguide/tasks.html", label: "Primary" },
    { title: "FastAPI and Celery Course", platform: "TestDriven.io", type: "Course",
      url: "https://testdriven.io/courses/fastapi-celery/", label: "Selective" },
  ],
  33: [
    { title: "Backend Engineering Videos", platform: "Hussein Nasser", type: "Playlist",
      url: "https://www.youtube.com/@hnasr/videos", label: "Primary" },
    { title: "System Design Videos", platform: "ByteByteGo", type: "Playlist",
      url: "https://www.youtube.com/@ByteByteGo/videos", label: "Selective" },
  ],
  35: [
    { title: "Graph Theory Playlist", platform: "William Fiset", type: "Playlist",
      url: "https://www.youtube.com/playlist?list=PLDV1Zeh2NRsBI1C-mR6ZhHTyfoEJWlxvq", label: "Primary" },
    { title: "Algorithms Playlist", platform: "Abdul Bari", type: "Playlist",
      url: "https://www.youtube.com/playlist?list=PLDN4rrl48XKpZkf03iYFl-O29szjTrs_O", label: "Selective" },
    { title: "NeetCode Roadmap", platform: "NeetCode", type: "Documentation",
      url: "https://neetcode.io/roadmap", label: "Reference" },
  ],
  37: [
    { title: "LLM Evals Playlists", platform: "Hamel Husain", type: "Playlist",
      url: "https://www.youtube.com/@hamelhusain7140/playlists", label: "Primary" },
    { title: "AI Evals: Everything You Need to Know", platform: "Hamel Husain", type: "Documentation",
      url: "https://hamel.dev/blog/posts/evals/", label: "Primary" },
    { title: "Agent Observability and Evaluation", platform: "LangChain Academy", type: "Course",
      url: "https://academy.langchain.com/courses/building-reliable-agents", label: "Selective" },
  ],
  38: [
    { title: "LangSmith Essentials", platform: "LangChain Academy", type: "Course",
      url: "https://academy.langchain.com/courses/quickstart-langsmith-essentials", label: "Primary" },
    { title: "Getting Started", platform: "OpenTelemetry", type: "Documentation",
      url: "https://opentelemetry.io/docs/getting-started/", label: "Reference" },
  ],
  39: [
    { title: "OWASP Top 10 for LLM Applications", platform: "OWASP", type: "Documentation",
      url: "https://genai.owasp.org/llm-top-10/", label: "Primary" },
    { title: "Prompt Injection", platform: "Simon Willison", type: "Documentation",
      url: "https://simonwillison.net/tags/prompt-injection/", label: "Selective" },
  ],
  41: [
    { title: "LLM Bootcamp", platform: "Full Stack Deep Learning", type: "Course",
      url: "https://fullstackdeeplearning.com/llm-bootcamp/spring-2023/", label: "Primary" },
    { title: "LLMOps", platform: "Full Stack Deep Learning", type: "Documentation",
      url: "https://fullstackdeeplearning.com/llm-bootcamp/spring-2023/llmops/", label: "Selective" },
  ],
  42: [
    { title: "NeetCode Roadmap", platform: "NeetCode", type: "Documentation",
      url: "https://neetcode.io/roadmap", label: "Reference" },
    { title: "Dynamic Programming Playlist", platform: "Striver", type: "Playlist",
      url: "https://www.youtube.com/playlist?list=PLgUwDviBIf0qUlt5H_kiKYaNSqJ81PMMY", label: "Selective" },
  ],
  43: [
    { title: "NeetCode Roadmap", platform: "NeetCode", type: "Documentation",
      url: "https://neetcode.io/roadmap", label: "Reference" },
    { title: "Striver A2Z DSA Course", platform: "take U forward", type: "Playlist",
      url: "https://www.youtube.com/playlist?list=PLgUwDviBIf0rENwdL0nEH0uGom9no0nyB", label: "Selective" },
  ],
  44: [
    { title: "LLM Bootcamp", platform: "Full Stack Deep Learning", type: "Course",
      url: "https://fullstackdeeplearning.com/llm-bootcamp/spring-2023/", label: "Reference" },
    { title: "System Design Playlist", platform: "Gaurav Sen", type: "Playlist",
      url: "https://www.youtube.com/playlist?list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX", label: "Primary" },
    { title: "Designing Machine Learning Systems Resources", platform: "Chip Huyen", type: "Documentation",
      url: "https://huyenchip.com/machine-learning-systems-design/toc.html", label: "Selective" },
  ],
};

/* Verified LeetCode slugs for every named DSA problem in the roadmap, keyed by the
   exact title string used in DAYS[].dsa. Custom implementation exercises (no LeetCode
   equivalent) are intentionally absent — the UI renders those as plain, non-linked text. */

const DSA_LEETCODE_SLUGS = {
  "Contains Duplicate": "contains-duplicate",
  "Valid Anagram": "valid-anagram",
  "Two Sum": "two-sum",
  "Group Anagrams": "group-anagrams",
  "Top K Frequent Elements": "top-k-frequent-elements",
  "Majority Element": "majority-element",
  "Product of Array Except Self": "product-of-array-except-self",
  "Find Pivot Index": "find-pivot-index",
  "Range Sum Query": "range-sum-query-immutable",
  "Maximum Subarray": "maximum-subarray",
  "Subarray Sum Equals K": "subarray-sum-equals-k",
  "Continuous Subarray Sum": "continuous-subarray-sum",
  "Longest Common Prefix": "longest-common-prefix",
  "String Compression": "string-compression",
  "Encode and Decode Strings": "encode-and-decode-strings",
  "Set Matrix Zeroes": "set-matrix-zeroes",
  "Spiral Matrix": "spiral-matrix",
  "Merge Intervals": "merge-intervals",
  "Timed: Group Anagrams": "group-anagrams",
  "Timed: Product Except Self": "product-of-array-except-self",
  "Timed: Subarray Sum Equals K": "subarray-sum-equals-k",

  "Valid Palindrome": "valid-palindrome",
  "Two Sum II": "two-sum-ii-input-array-is-sorted",
  "Remove Duplicates from Sorted Array": "remove-duplicates-from-sorted-array",
  "Container With Most Water": "container-with-most-water",
  "3Sum": "3sum",
  "Squares of a Sorted Array": "squares-of-a-sorted-array",
  "Maximum Average Subarray I": "maximum-average-subarray-i",
  "Permutation in String": "permutation-in-string",
  "Find All Anagrams": "find-all-anagrams-in-a-string",
  "Longest Substring Without Repeating Characters": "longest-substring-without-repeating-characters",
  "Longest Repeating Character Replacement": "longest-repeating-character-replacement",
  "Minimum Size Subarray Sum": "minimum-size-subarray-sum",
  "Minimum Window Substring": "minimum-window-substring",
  "Fruit Into Baskets": "fruit-into-baskets",
  "Max Consecutive Ones III": "max-consecutive-ones-iii",
  "Insert Interval": "insert-interval",
  "Non-overlapping Intervals": "non-overlapping-intervals",
  "Meeting Rooms II": "meeting-rooms-ii",
  "Timed: 3Sum": "3sum",
  "Timed: Longest Substring": "longest-substring-without-repeating-characters",
  "Timed: Minimum Window": "minimum-window-substring",

  "Valid Parentheses": "valid-parentheses",
  "Min Stack": "min-stack",
  "Evaluate Reverse Polish Notation": "evaluate-reverse-polish-notation",
  "Daily Temperatures": "daily-temperatures",
  "Next Greater Element I": "next-greater-element-i",
  "Largest Rectangle in Histogram": "largest-rectangle-in-histogram",
  "Binary Search": "binary-search",
  "Search Insert Position": "search-insert-position",
  "First and Last Position": "find-first-and-last-position-of-element-in-sorted-array",
  "Search in Rotated Sorted Array": "search-in-rotated-sorted-array",
  "Find Minimum in Rotated Array": "find-minimum-in-rotated-sorted-array",
  "Koko Eating Bananas": "koko-eating-bananas",
  "Reverse Linked List": "reverse-linked-list",
  "Merge Two Sorted Lists": "merge-two-sorted-lists",
  "Linked List Cycle": "linked-list-cycle",
  "Remove Nth Node From End": "remove-nth-node-from-end-of-list",
  "Reorder List": "reorder-list",
  "Add Two Numbers": "add-two-numbers",
  "Timed: Daily Temperatures": "daily-temperatures",
  "Timed: Rotated Search": "search-in-rotated-sorted-array",
  "Timed: Reorder List": "reorder-list",

  "Maximum Depth of Binary Tree": "maximum-depth-of-binary-tree",
  "Same Tree": "same-tree",
  "Invert Binary Tree": "invert-binary-tree",
  "Diameter of Binary Tree": "diameter-of-binary-tree",
  "Balanced Binary Tree": "balanced-binary-tree",
  "Subtree of Another Tree": "subtree-of-another-tree",
  "Binary Tree Level Order": "binary-tree-level-order-traversal",
  "Right Side View": "binary-tree-right-side-view",
  "Zigzag Traversal": "binary-tree-zigzag-level-order-traversal",
  "Validate BST": "validate-binary-search-tree",
  "Kth Smallest in BST": "kth-smallest-element-in-a-bst",
  "LCA of BST": "lowest-common-ancestor-of-a-binary-search-tree",
  "LCA of Binary Tree": "lowest-common-ancestor-of-a-binary-tree",
  "Binary Tree Maximum Path Sum": "binary-tree-maximum-path-sum",
  "Serialize/Deserialize Tree": "serialize-and-deserialize-binary-tree",
  "Kth Largest Element": "kth-largest-element-in-an-array",
  "Find Median from Data Stream": "find-median-from-data-stream",
  "Implement Trie": "implement-trie-prefix-tree",
  "Timed: Level Order": "binary-tree-level-order-traversal",
  "Timed: Validate BST": "validate-binary-search-tree",
  "Timed: LCA": "lowest-common-ancestor-of-a-binary-tree",

  "Path Exists in Graph": "find-if-path-exists-in-graph",
  "Number of Provinces": "number-of-provinces",
  "Flood Fill": "flood-fill",
  "Number of Islands": "number-of-islands",
  "Max Area of Island": "max-area-of-island",
  "Surrounded Regions": "surrounded-regions",
  "Clone Graph": "clone-graph",
  "Rotting Oranges": "rotting-oranges",
  "Pacific Atlantic Water Flow": "pacific-atlantic-water-flow",
  "Course Schedule": "course-schedule",
  "Course Schedule II": "course-schedule-ii",
  "Eventual Safe States": "find-eventual-safe-states",
  "Redundant Connection": "redundant-connection",
  "Accounts Merge": "accounts-merge",
  "Connected Components": "number-of-connected-components-in-an-undirected-graph",
  "Network Delay Time": "network-delay-time",
  "Cheapest Flights Within K Stops": "cheapest-flights-within-k-stops",
  "Path With Minimum Effort": "path-with-minimum-effort",
  "Timed: Number of Islands": "number-of-islands",
  "Timed: Course Schedule": "course-schedule",
  "Timed: Network Delay": "network-delay-time",

  "Subsets": "subsets",
  "Subsets II": "subsets-ii",
  "Combination Sum": "combination-sum",
  "Permutations": "permutations",
  "Letter Combinations": "letter-combinations-of-a-phone-number",
  "Word Search": "word-search",
  "Jump Game": "jump-game",
  "Gas Station": "gas-station",
  "Partition Labels": "partition-labels",
  "Climbing Stairs": "climbing-stairs",
  "House Robber": "house-robber",
  "Coin Change": "coin-change",
  "Longest Increasing Subsequence": "longest-increasing-subsequence",
  "Unique Paths": "unique-paths",
  "Longest Common Subsequence": "longest-common-subsequence",
  "Edit Distance": "edit-distance",
  "Partition Equal Subset Sum": "partition-equal-subset-sum",
  "Target Sum": "target-sum",
  "Timed: Combination Sum": "combination-sum",
  "Timed: Coin Change": "coin-change",
  "Timed: LCS": "longest-common-subsequence",

  "Single Number": "single-number",
  "Number of 1 Bits": "number-of-1-bits",
  "Counting Bits": "counting-bits",
  "Missing Number": "missing-number",
  "Sum of Two Integers": "sum-of-two-integers",
  "Minimum Arrows to Burst Balloons": "minimum-number-of-arrows-to-burst-balloons",
  "LRU Cache": "lru-cache",
  "Time Based Key-Value Store": "time-based-key-value-store",
  "Design Hit Counter": "design-hit-counter",
};

const DAYS = [
  { day: 1, week: 1, date: "Sunday, 13 September 2026", title: "Python for production",
    learn: "Mutability, comprehensions, functions, exceptions, modules, virtual environments, typing.",
    build: "Create the Agent Reliability Lab repository; configure linting, typing, pytest and settings.",
    dsa: ["Contains Duplicate", "Valid Anagram", "Two Sum"],
    ship: "Repository boots locally; 5 tests pass." },
  { day: 2, week: 1, date: "Monday, 14 September 2026", title: "Objects and clean boundaries",
    learn: "Dataclasses, protocols, abstract interfaces, decorators, generators and context managers.",
    build: "Create domain models and repository interfaces for projects, datasets, prompts and executions.",
    dsa: ["Group Anagrams", "Top K Frequent Elements", "Majority Element"],
    ship: "Interfaces documented; fake repository tested." },
  { day: 3, week: 1, date: "Tuesday, 15 September 2026", title: "Async Python",
    learn: "Coroutines, tasks, gather, cancellation, semaphores, timeouts, threads vs processes.",
    build: "Call three simulated services sequentially and concurrently; record latency and partial failures.",
    dsa: ["Product of Array Except Self", "Find Pivot Index", "Range Sum Query"],
    ship: "Concurrency benchmark plus timeout tests." },
  { day: 4, week: 1, date: "Wednesday, 16 September 2026", title: "FastAPI and Pydantic",
    learn: "Routing, request/response models, dependency injection, validation, middleware and errors.",
    build: "Build project, dataset and experiment endpoints with central exception handling.",
    dsa: ["Maximum Subarray", "Subarray Sum Equals K", "Continuous Subarray Sum"],
    ship: "OpenAPI works; invalid requests return controlled errors." },
  { day: 5, week: 1, date: "Thursday, 17 September 2026", title: "PostgreSQL and persistence",
    learn: "SQL, indexes, transactions, SQLAlchemy sessions, connection pools and Alembic.",
    build: "Persist core entities; add migrations, pagination and transaction rollback tests.",
    dsa: ["Longest Common Prefix", "String Compression", "Encode and Decode Strings"],
    ship: "Schema reproducible from zero; integration tests pass." },
  { day: 6, week: 1, date: "Friday, 18 September 2026", title: "ML metrics and similarity",
    learn: "Train/validation/test, overfitting, precision, recall, F1, vectors and cosine similarity.",
    build: "Implement cosine similarity with NumPy and a tiny in-memory top-k search.",
    dsa: ["Set Matrix Zeroes", "Spiral Matrix", "Merge Intervals"],
    ship: "Metrics notebook/script plus unit tests." },
  { day: 7, week: 1, date: "Saturday, 19 September 2026", title: "Weekly integration and mock",
    learn: "Review every concept; no new framework.",
    build: "Docker Compose API + PostgreSQL; refactor weak code; record a 10-minute explanation.",
    dsa: ["Timed: Group Anagrams", "Timed: Product Except Self", "Timed: Subarray Sum Equals K"],
    ship: "Week gate passed without notes; backlog recorded." },

  { day: 8, week: 2, date: "Sunday, 20 September 2026", title: "Neural-network intuition",
    learn: "Neurons, activations, loss, gradient descent, backpropagation, training vs inference.",
    build: "Implement a tiny neural network or follow micrograd sections; document forward/backward flow.",
    dsa: ["Valid Palindrome", "Two Sum II", "Remove Duplicates from Sorted Array"],
    ship: "One-page neural-network explanation." },
  { day: 9, week: 2, date: "Monday, 21 September 2026", title: "Tokens and embeddings",
    learn: "Tokenization, vocabulary, token IDs, embeddings, context windows and positional information.",
    build: "Build a basic tokenizer experiment; compare token counts across inputs.",
    dsa: ["Container With Most Water", "3Sum", "Squares of a Sorted Array"],
    ship: "Tokenizer notes and cost implications." },
  { day: 10, week: 2, date: "Tuesday, 22 September 2026", title: "Attention and transformers",
    learn: "Q/K/V, scaled dot-product attention, heads, causal mask, residuals, normalisation and FFN.",
    build: "Implement single-head causal attention in PyTorch/NumPy and test mask behaviour.",
    dsa: ["Maximum Average Subarray I", "Permutation in String", "Find All Anagrams"],
    ship: "Attention tensor shapes explained aloud." },
  { day: 11, week: 2, date: "Wednesday, 23 September 2026", title: "Generation and prompting",
    learn: "Autoregressive decoding, temperature, top-p, hallucination, system/user roles and context design.",
    build: "Create prompt versions and model configurations in PostgreSQL; compare deterministic cases.",
    dsa: ["Longest Substring Without Repeating Characters", "Longest Repeating Character Replacement", "Minimum Size Subarray Sum"],
    ship: "Prompt comparison with measured outputs." },
  { day: 12, week: 2, date: "Thursday, 24 September 2026", title: "Structured outputs",
    learn: "JSON Schema, Pydantic validation, extraction, repair policy and refusal handling.",
    build: "Build structured candidate/document extraction; reject malformed output safely.",
    dsa: ["Minimum Window Substring", "Fruit Into Baskets", "Max Consecutive Ones III"],
    ship: "Schema-valid output and negative tests." },
  { day: 13, week: 2, date: "Friday, 25 September 2026", title: "Tool calling from scratch",
    learn: "Tool schemas, registry, permissions, loop limits, observations and final responses.",
    build: "Implement manual tool loop with search, deterministic score and unknown-tool rejection.",
    dsa: ["Insert Interval", "Non-overlapping Intervals", "Meeting Rooms II"],
    ship: "Agent loop passes happy-path and cycle tests." },
  { day: 14, week: 2, date: "Saturday, 26 September 2026", title: "Provider abstraction and mock",
    learn: "Streaming, token/cost tracking, retries, caching and provider independence.",
    build: "Add provider interface, deterministic fake, SSE streaming and execution records.",
    dsa: ["Timed: 3Sum", "Timed: Longest Substring", "Timed: Minimum Window"],
    ship: "Five-minute transformer answer plus live tool demo." },

  { day: 15, week: 3, date: "Sunday, 27 September 2026", title: "Document ingestion",
    learn: "Extraction, cleaning, metadata, hashing, deduplication and incremental indexing.",
    build: "Upload documents; store ingestion status and content hashes.",
    dsa: ["Valid Parentheses", "Min Stack", "Evaluate Reverse Polish Notation"],
    ship: "Duplicate uploads are idempotent." },
  { day: 16, week: 3, date: "Monday, 28 September 2026", title: "Chunking",
    learn: "Fixed, recursive, structural, semantic and parent-child chunking; overlap trade-offs.",
    build: "Implement two chunkers and generate comparable chunk statistics.",
    dsa: ["Daily Temperatures", "Next Greater Element I", "Largest Rectangle in Histogram"],
    ship: "Chunk tests cover boundaries and empty input." },
  { day: 17, week: 3, date: "Tuesday, 29 September 2026", title: "Embeddings and pgvector",
    learn: "Embedding selection, dimensionality, cosine/dot distance, indexing and batch embedding.",
    build: "Persist chunks and embeddings in pgvector; build dense top-k retrieval.",
    dsa: ["Binary Search", "Search Insert Position", "First and Last Position"],
    ship: "Dense search returns sources with latency." },
  { day: 18, week: 3, date: "Wednesday, 30 September 2026", title: "Sparse and hybrid retrieval",
    learn: "Full-text/BM25 intuition, reciprocal-rank fusion, metadata filters and query rewriting.",
    build: "Add PostgreSQL text search and hybrid rank fusion.",
    dsa: ["Search in Rotated Sorted Array", "Find Minimum in Rotated Array", "Koko Eating Bananas"],
    ship: "Dense vs hybrid results captured." },
  { day: 19, week: 3, date: "Thursday, 01 October 2026", title: "Reranking and citations",
    learn: "Cross-encoder intuition, contextual compression, lost-in-middle and grounded citations.",
    build: "Add reranking and citation mapping; refuse when evidence is insufficient.",
    dsa: ["Reverse Linked List", "Merge Two Sorted Lists", "Linked List Cycle"],
    ship: "Answers contain verifiable source identifiers." },
  { day: 20, week: 3, date: "Friday, 02 October 2026", title: "Retrieval evaluation",
    learn: "Ground truth, Recall@k, Precision@k, MRR, faithfulness and answer correctness.",
    build: "Create 30 labelled queries; compare chunk sizes, top-k, hybrid and reranking.",
    dsa: ["Remove Nth Node From End", "Reorder List", "Add Two Numbers"],
    ship: "Evaluation report contains real numbers." },
  { day: 21, week: 3, date: "Saturday, 03 October 2026", title: "RAG defence mock",
    learn: "Deletion, re-indexing, tenant boundaries, cache invalidation and failure analysis.",
    build: "Run failure cases; fix weakest configuration; record architecture walkthrough.",
    dsa: ["Timed: Daily Temperatures", "Timed: Rotated Search", "Timed: Reorder List"],
    ship: "Explain why chosen RAG configuration wins." },

  { day: 22, week: 4, date: "Sunday, 04 October 2026", title: "Agent patterns",
    learn: "ReAct, router, planner-executor, evaluator-optimizer, supervisor and deterministic workflows.",
    build: "Map three use cases to the simplest valid pattern; implement a router.",
    dsa: ["Maximum Depth of Binary Tree", "Same Tree", "Invert Binary Tree"],
    ship: "Pattern decision document completed." },
  { day: 23, week: 4, date: "Monday, 05 October 2026", title: "LangGraph fundamentals",
    learn: "Typed state, nodes, edges, conditional routing, reducers and streaming.",
    build: "Convert the manual loop into a small state graph.",
    dsa: ["Diameter of Binary Tree", "Balanced Binary Tree", "Subtree of Another Tree"],
    ship: "Graph tests assert routes and state." },
  { day: 24, week: 4, date: "Tuesday, 06 October 2026", title: "Persistence and durable execution",
    learn: "Checkpoints, thread IDs, interrupt/resume, replay and deterministic side effects.",
    build: "Persist checkpoints; stop process mid-run and resume safely.",
    dsa: ["Binary Tree Level Order", "Right Side View", "Zigzag Traversal"],
    ship: "Restart recovery demonstrated." },
  { day: 25, week: 4, date: "Wednesday, 07 October 2026", title: "Memory",
    learn: "Working state, conversation memory, semantic memory, episodic memory, summarisation and forgetting.",
    build: "Implement bounded short-term state and project-level semantic memory.",
    dsa: ["Validate BST", "Kth Smallest in BST", "LCA of BST"],
    ship: "Memory policy and retention limits documented." },
  { day: 26, week: 4, date: "Thursday, 08 October 2026", title: "Human in the loop",
    learn: "Approval, edit/reject, auditability, permissions and destructive action boundaries.",
    build: "Add approval interrupt for a simulated write tool; resume from checkpoint.",
    dsa: ["LCA of Binary Tree", "Binary Tree Maximum Path Sum", "Serialize/Deserialize Tree"],
    ship: "No write occurs without explicit approval." },
  { day: 27, week: 4, date: "Friday, 09 October 2026", title: "MCP and tool safety",
    learn: "JSON-RPC concept, servers, clients, resources/tools, schemas, auth and trust boundaries.",
    build: "Build a minimal Python MCP server exposing two read-only tools.",
    dsa: ["Kth Largest Element", "Find Median from Data Stream", "Implement Trie"],
    ship: "MCP tools validated and audited." },
  { day: 28, week: 4, date: "Saturday, 10 October 2026", title: "Agent architecture mock",
    learn: "Cycles, tool timeouts, parallel fan-out, partial failures and multi-agent skepticism.",
    build: "Compare manual loop vs LangGraph; remove unjustified complexity.",
    dsa: ["Timed: Level Order", "Timed: Validate BST", "Timed: LCA"],
    ship: "Whiteboard and defend one-agent design." },

  { day: 29, week: 5, date: "Sunday, 11 October 2026", title: "Graph traversal",
    learn: "Adjacency lists, BFS, DFS, components and complexity O(V+E).",
    build: "Move document ingestion to a task interface; model states explicitly.",
    dsa: ["Path Exists in Graph", "Number of Provinces", "Flood Fill"],
    ship: "Task state machine documented." },
  { day: 30, week: 5, date: "Monday, 12 October 2026", title: "RabbitMQ fundamentals",
    learn: "Producer, exchange, binding, queue, consumer, acknowledgement, prefetch and DLQ.",
    build: "Add RabbitMQ and publish/consume a durable example task.",
    dsa: ["Number of Islands", "Max Area of Island", "Surrounded Regions"],
    ship: "Messages survive normal worker restart." },
  { day: 31, week: 5, date: "Tuesday, 13 October 2026", title: "Celery execution",
    learn: "Workers, broker, result backend, task routing, groups, chains and progress.",
    build: "Move ingestion and evaluation into Celery; expose progress endpoint.",
    dsa: ["Clone Graph", "Rotting Oranges", "Pacific Atlantic Water Flow"],
    ship: "API remains responsive during long jobs." },
  { day: 32, week: 5, date: "Wednesday, 14 October 2026", title: "Retries and idempotency",
    learn: "Backoff, jitter, time limits, duplicate delivery, idempotency keys and poison messages.",
    build: "Add idempotency and retry policies; deliberately deliver duplicates.",
    dsa: ["Course Schedule", "Course Schedule II", "Eventual Safe States"],
    ship: "Duplicate execution causes no duplicate side effect." },
  { day: 33, week: 5, date: "Thursday, 15 October 2026", title: "Resilience patterns",
    learn: "Timeout, circuit breaker, fallback, bulkhead, backpressure and graceful degradation.",
    build: "Wrap providers/tools with timeouts and circuit breaker; test fallback.",
    dsa: ["Redundant Connection", "Accounts Merge", "Connected Components"],
    ship: "Failure policy represented in tests." },
  { day: 34, week: 5, date: "Friday, 16 October 2026", title: "Shortest paths and latency budgets",
    learn: "BFS, Dijkstra, Bellman-Ford; system latency budgets and parallel calls.",
    build: "Implement voice-agent backend fan-out with cached/partial responses.",
    dsa: ["Network Delay Time", "Cheapest Flights Within K Stops", "Path With Minimum Effort"],
    ship: "Slow CRM does not freeze conversation." },
  { day: 35, week: 5, date: "Saturday, 17 October 2026", title: "Chaos day and mock",
    learn: "Kill workers, restart broker, force 429, malformed output, database loss and cancellation.",
    build: "Run eight failure drills and record observed recovery.",
    dsa: ["Timed: Number of Islands", "Timed: Course Schedule", "Timed: Network Delay"],
    ship: "TrueFan-style architecture answer recorded." },

  { day: 36, week: 6, date: "Sunday, 18 October 2026", title: "Backtracking and eval datasets",
    learn: "Golden datasets, representative sampling, deterministic checks and human labels.",
    build: "Create 30 agent cases with expected tools, constraints and outcomes.",
    dsa: ["Subsets", "Subsets II", "Combination Sum"],
    ship: "Evaluation dataset versioned." },
  { day: 37, week: 6, date: "Monday, 19 October 2026", title: "LLM-as-judge",
    learn: "Rubrics, structured scores, pairwise comparison, bias, calibration and human review.",
    build: "Implement deterministic validators plus judge; manually audit disagreements.",
    dsa: ["Permutations", "Letter Combinations", "Word Search"],
    ship: "Judge agreement and failures documented." },
  { day: 38, week: 6, date: "Tuesday, 20 October 2026", title: "Observability",
    learn: "Logs, metrics, traces, correlation IDs, P50/P95/P99, token/cost and failure taxonomies.",
    build: "Trace API, Celery, retrieval, model and tool spans end-to-end.",
    dsa: ["Jump Game", "Gas Station", "Partition Labels"],
    ship: "One trace explains a complete execution." },
  { day: 39, week: 6, date: "Wednesday, 21 October 2026", title: "AI security",
    learn: "Prompt injection, indirect injection, exfiltration, excessive agency, PII and tenant isolation.",
    build: "Create adversarial test suite; enforce tool allowlist, RBAC and PII redaction.",
    dsa: ["Climbing Stairs", "House Robber", "Coin Change"],
    ship: "Attacks fail safely and are logged." },
  { day: 40, week: 6, date: "Thursday, 22 October 2026", title: "Advanced DP and regression",
    learn: "State, transition, base cases, memoisation, tabulation and regression gates.",
    build: "Run eval suite in CI; block deployment on critical regression.",
    dsa: ["Longest Increasing Subsequence", "Unique Paths", "Longest Common Subsequence"],
    ship: "CI produces evaluation summary." },
  { day: 41, week: 6, date: "Friday, 23 October 2026", title: "Deployment",
    learn: "Multi-stage images, secrets, migrations, health checks, rolling deploy and rollback.",
    build: "Deploy API, workers, PostgreSQL/pgvector, Redis and broker configuration.",
    dsa: ["Edit Distance", "Partition Equal Subset Sum", "Target Sum"],
    ship: "Public demo and health checks work." },
  { day: 42, week: 6, date: "Saturday, 24 October 2026", title: "Operations mock",
    learn: "Incident response, stale cache, provider outage, prompt rollback and cost spike.",
    build: "Run incident game; produce dashboard and short postmortem.",
    dsa: ["Timed: Combination Sum", "Timed: Coin Change", "Timed: LCS"],
    ship: "System remains explainable under failure." },

  { day: 43, week: 7, date: "Sunday, 25 October 2026", title: "Bit manipulation and consolidation",
    learn: "XOR, masks, shifts; consolidate Python, LLM, RAG and agent notes.",
    build: "Create one-page sheets: Python async, transformers, RAG and agents.",
    dsa: ["Single Number", "Number of 1 Bits", "Counting Bits"],
    ship: "Four sheets completed from memory." },
  { day: 44, week: 7, date: "Monday, 26 October 2026", title: "System design I",
    learn: "Requirements, scale, APIs, data model, components, latency, failure and cost.",
    build: "Design the live-data voice agent and multi-tenant enterprise RAG system.",
    dsa: ["Missing Number", "Sum of Two Integers", "Minimum Arrows to Burst Balloons"],
    ship: "Two 45-minute designs recorded." },
  { day: 45, week: 7, date: "Tuesday, 27 October 2026", title: "System design II",
    learn: "Evaluation platform, recruitment agent, human escalation and safe actions.",
    build: "Design one-million-case batch evaluation and Stellar recruiting workflows.",
    dsa: ["LRU Cache", "Time Based Key-Value Store", "Design Hit Counter"],
    ship: "Trade-offs and capacity estimates included." },
  { day: 46, week: 7, date: "Wednesday, 28 October 2026", title: "Python coding mock",
    learn: "Communicate brute force, optimal approach, correctness, complexity and tests.",
    build: "Implement async fan-out, retry decorator, TTL cache and tool loop without AI.",
    dsa: ["Unseen array/string Medium", "Unseen tree/graph Medium"],
    ship: "90-minute mock scored honestly." },
  { day: 47, week: 7, date: "Thursday, 29 October 2026", title: "AI fundamentals mock",
    learn: "Transformers, embeddings, RAG, tools, agents, evals, security and deployment.",
    build: "Answer 50 rapid questions; repair weak explanations.",
    dsa: ["Unseen binary-search Medium", "Unseen graph Medium"],
    ship: "At least 80% strong answers." },
  { day: 48, week: 7, date: "Friday, 30 October 2026", title: "Project defence and profile",
    learn: "Problem, architecture, request trace, measurements, failures, decisions and limitations.",
    build: "Record five-minute demo; update resume, LinkedIn, README and architecture diagram.",
    dsa: ["Cosine similarity", "Top-k with heap", "Token-bucket limiter"],
    ship: "Artifacts show evidence, not buzzwords." },
  { day: 49, week: 7, date: "Saturday, 31 October 2026", title: "Final interview day",
    learn: "No new study. Demonstrate integrated competence.",
    build: "Run coding, AI fundamentals, system design, project deep dive and behavioural mocks.",
    dsa: ["One unseen Medium", "Bounded-concurrency model client", "Streaming event aggregator"],
    ship: "Scorecard complete; begin targeted applications." },
];

// Attach resources onto their day (kept as a separate lookup above so the DAYS
// array itself stays a plain transcription of the roadmap content).
DAYS.forEach((d) => {
  if (RESOURCES_BY_DAY[d.day]) d.resources = RESOURCES_BY_DAY[d.day];
});

const DSA_OS = {
  title: "DSA Operating System",
  subtitle: "How problems are counted",
  intro: "A problem counts only when you can reproduce the approach and explain correctness. Recognising a solution after seeing it is not mastery.",
  resultTable: [
    { result: "A", meaning: "Optimal solution without help", revisit: "14 days" },
    { result: "B", meaning: "Solved after a small hint", revisit: "7 days" },
    { result: "C", meaning: "Needed the approach", revisit: "1, 3 and 7 days" },
    { result: "D", meaning: "Could not reproduce", revisit: "Learn prerequisite; retry tomorrow" },
  ],
  mustInclude: [
    "Clarified constraints and edge cases",
    "Brute-force idea and complexity",
    "Optimal pattern and invariant",
    "Correct Python implementation",
    "Time and space complexity",
    "Dry run",
    "At least three tests",
  ],
  patternPrompts: [
    { signal: "Frequency, duplicates, lookup", pattern: "Hash map / set" },
    { signal: "Contiguous range", pattern: "Sliding window / prefix sum" },
    { signal: "Sorted data", pattern: "Two pointers / binary search" },
    { signal: "Minimum feasible maximum", pattern: "Binary search on answer" },
    { signal: "Next greater/smaller", pattern: "Monotonic stack" },
    { signal: "Top-k / repeated extrema", pattern: "Heap" },
    { signal: "Connectivity", pattern: "DFS / BFS / union-find" },
    { signal: "Dependencies", pattern: "Topological sort" },
    { signal: "All combinations", pattern: "Backtracking" },
    { signal: "Overlapping choices", pattern: "Dynamic programming" },
  ],
};

const CONTENT_PATH = {
  title: "Curated Content Path",
  subtitle: "Watch less. Build more.",
  intro: "Use these teachers as support. Do not complete entire channels or collect certificates. The project and interview gates decide progress.",
  resources: [
    { area: "Python / APIs", value: "Dave Ebbelaar: Python for AI & Agents; mCoding AsyncIO; FastAPI and Pydantic official docs" },
    { area: "LLM foundations", value: "Andrej Karpathy: Deep Dive into LLMs, Let's Build GPT, Tokenizer; 3Blue1Brown attention" },
    { area: "RAG", value: "LangChain: RAG From Scratch (Lance Martin); pgvector docs; retrieval experiments" },
    { area: "Agents", value: "Dave Ebbelaar pure-Python agents; LangChain Academy: Introduction to LangGraph" },
    { area: "Reliability", value: "Hussein Nasser backend concepts; Celery and RabbitMQ official documentation" },
    { area: "Evals / ops", value: "LangChain Academy observability/evaluation; OWASP LLM Top 10; OpenTelemetry docs" },
    { area: "System design", value: "Full Stack Deep Learning; Chip Huyen; selected Gaurav Sen / ByteByteGo concepts" },
  ],
  ebbelaarNote: "Use him as an implementation teacher: selected Python for AI & Agents material in Week 1, pure-Python agents in Week 2, Agentic RAG in Week 3 and reliable-agent architecture in Week 4. He is not sufficient alone for transformer internals, distributed systems, security, deep evaluation or system design.",
  blacklist: [
    "Avoid: No-code agent tutorials",
    "Avoid: Build-five-agents-in-one-hour videos",
    "Avoid: Prompt engineering certificates",
    "Avoid: Framework demos with prewritten code",
    "Avoid: Unrelated new projects",
    "Avoid: Advanced CUDA/model training during this sprint",
    "Avoid: Endless tool comparison and roadmap redesign",
  ],
};

const FINAL_READINESS = {
  title: "Day 49 Scorecard",
  subtitle: "Proof required before claiming readiness",
  items: [
    "One deployed production-style Agent Reliability Lab",
    "Public architecture and trade-off documentation",
    "At least 50 backend tests",
    "At least 30 labelled retrieval evaluation cases",
    "At least 30 end-to-end agent evaluation cases",
    "Measured retrieval quality, answer quality, latency and cost",
    "Eight recorded failure-injection experiments",
    "Safe tool approvals, tenant boundaries and injection tests",
    "A five-minute demo video",
    "Two defensible project stories: Agent Reliability Lab and Stellar recruiting platform",
    "At least six timed DSA mocks and seven AI/system-design mocks",
    "AI-focused resume, LinkedIn and GitHub README",
    "Active, targeted Applied AI applications before the sprint ends",
  ],
  positioning: "Applied AI Engineer with two years of software-product engineering experience, specialising in production agent workflows, reliable LLM systems and end-to-end AI products.",
  standard: "You built it, measured it, broke it, fixed it, deployed it - and can defend every important decision under questioning.",
};

const META = {
  productName: "Mirror49",
  fullTitle: "49-Day Applied AI Engineer Execution Roadmap",
  subtitle: "AI engineering + implementation + DSA + system design + interview conversion",
  dateRange: "13 September - 31 October 2026",
  preparedFor: "Utkarsh Katiyar",
  contractLine: "This is not a reading list. It is a contract: build, measure, break, repair, explain and apply.",
};
